env:
  es6: true
  node: true
  jest/globals: true
parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    impliedStrict: true
  sourceType: module
extends: 'eslint:recommended'
plugins:
  - jest
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - error
    -
      argsIgnorePattern: "^_"
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
